#----------------------------------------------------------------------------
# Setup the project
cmake_minimum_required(VERSION 3.10)
if(${CMAKE_VERSION} VERSION_LESS 3.12)
  cmake_policy(VERSION ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION})
endif()
set(PROJ_NAME g4beginner)
project(${PROJ_NAME})
#----------------------------------------------------------------------------
# Find Geant4 package, activating all available UI and Vis drivers by default
# You can set WITH_GEANT4_UIVIS to OFF via the command line or ccmake/cmake-gui
# to build a batch mode only executable
#
set(CMAKE_PREFIX_PATH $ENV{G4CMPINSTALL}/../..)
find_package(G4CMP REQUIRED)
option(WITH_GEANT4_UIVIS "Build example with Geant4 UI and Vis drivers" ON)
if(WITH_GEANT4_UIVIS)
  find_package(Geant4 REQUIRED ui_all vis_all)
else()
  find_package(Geant4 REQUIRED)
endif()

#----------------------------------------------------------------------------
# Setup Geant4 include directories and compile definitions
# Setup include directory for this project
#
include(${Geant4_USE_FILE})
include(${G4CMP_USE_FILE})
include_directories(${PROJECT_SOURCE_DIR}/include)

set(CMAKE_CXX_STANDARD_REQUIRED True)
# Use same C++ version as was used for G4CMP
if (NOT DEFINED CMAKE_CXX_STANDARD) # Only if user did not specify
    set(CMAKE_CXX_STANDARD ${G4CMP_CXX_STANDARD})
endif()

message(STATUS "Found G4CMP: ${G4CMP_VERSION}")
message(STATUS "Setting CMAKE_CXX_STANDARD: ${CMAKE_CXX_STANDARD}")

#----------------------------------------------------------------------------
# Locate sources and headers for this project
# NB: headers are included so they will show up in IDEs
#
file(GLOB sources ${PROJECT_SOURCE_DIR}/src/*.cc)
file(GLOB headers ${PROJECT_SOURCE_DIR}/include/*.hh)

#----------------------------------------------------------------------------
# Add the executable, and link it to the Geant4 libraries
#
add_executable(${PROJ_NAME} ${PROJ_NAME}.cc ${sources} ${headers})
target_link_libraries(${PROJ_NAME} ${Geant4_LIBRARIES} ${G4CMP_LIBRARIES})

#----------------------------------------------------------------------------
# Copy all scripts to the build directory, i.e. the directory in which we
# build g4beginner. This is so that we can run the executable directly because it
# relies on these scripts being in the current working directory.
set(G4BEGINNER_MACROS
  g4cmp_electrons_100um.mac
  g4cmp_phonons_100um.mac
  g4cmp_electrons_300um.mac
  g4cmp_phonons_300um.mac
  init_vis.mac
  vis.mac
)
set(G4BEGINNER_SCRIPTS
  g4cmp_electrons_interface_hits.C
  g4cmp_phonons_interface_hits.C
  g4cmp_phonons_pairbreaking_summary.C
)

foreach(_script ${G4BEGINNER_SCRIPTS})
  configure_file(
    ${PROJECT_SOURCE_DIR}/scripts/${_script}
    ${PROJECT_BINARY_DIR}/${_script}
    COPYONLY
    )
endforeach()

foreach(_script ${G4BEGINNER_MACROS})
  configure_file(
    ${PROJECT_SOURCE_DIR}/G4Macros/${_script}
    ${PROJECT_BINARY_DIR}/${_script}
    COPYONLY
    )
endforeach()
#----------------------------------------------------------------------------
# Install the executable to 'bin' directory under CMAKE_INSTALL_PREFIX
#
install(TARGETS ${PROJ_NAME} DESTINATION bin)
