# Extracted GeoOpt-added material and volume lines.
# Source material file: engineering/geometry_optimization_20260704/01_geo_opt_s1_bottomw_b4c/geometry/Materials_DEMO2_DR_v3p5.geo
# Source geometry file: engineering/geometry_optimization_20260704/01_geo_opt_s1_bottomw_b4c/geometry/DEMO2_DR_v3p5_minpatch_centerfinger_megalib_proxy.geo

Material PlasticScintillator
PlasticScintillator.Density 1.03
PlasticScintillator.Component C 8
PlasticScintillator.Component H 8

Material BoratedPolyethylene5wtB
BoratedPolyethylene5wtB.Density 0.95
# Approximate 5 wt% natural boron in polyethylene: C:H:B ~= 1000:2000:68.
BoratedPolyethylene5wtB.Component C 1000
BoratedPolyethylene5wtB.Component H 2000
BoratedPolyethylene5wtB.Component B 68
# END GEO_OPT_S1_BOTTOMW_B4C_MATERIALS

Shape PCON GeoOpt_S1_PlasticFullWrap_SideShell_5mm_FullShellShape
GeoOpt_S1_PlasticFullWrap_SideShell_5mm_FullShellShape.Parameters 0 360 2 -15.15 27.4 27.9 15.15 27.4 27.9
Shape BRIK GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod03ReliefShape
GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod03ReliefShape.Parameters 4 4 0.75
Orientation GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod03ReliefOrientation
GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod03ReliefOrientation.Position -19.5 19.8 -14.9
Shape BRIK GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod04ReliefShape
GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod04ReliefShape.Parameters 4 4 0.75
Orientation GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod04ReliefOrientation
GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod04ReliefOrientation.Position -19.5 -19.8 -14.9
Shape Subtraction GeoOpt_S1_PlasticFullWrap_SideShell_5mm_ReliefStep01Shape
GeoOpt_S1_PlasticFullWrap_SideShell_5mm_ReliefStep01Shape.Parameters GeoOpt_S1_PlasticFullWrap_SideShell_5mm_FullShellShape GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod03ReliefShape GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod03ReliefOrientation
Shape Subtraction GeoOpt_S1_PlasticFullWrap_SideShell_5mm_ReliefStep02Shape
GeoOpt_S1_PlasticFullWrap_SideShell_5mm_ReliefStep02Shape.Parameters GeoOpt_S1_PlasticFullWrap_SideShell_5mm_ReliefStep01Shape GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod04ReliefShape GeoOpt_S1_PlasticFullWrap_SideShell_5mm_NF2Rod04ReliefOrientation
// Volume GeoOpt_S1_PlasticFullWrap_SideShell_5mm; role=Full-azimuth active plastic scintillator outer side skin; covers the side-window azimuth as a charged-particle sentinel instead of using the earlier low-statistics segmented S1 sector proxy; includes two local NF2 outer-support rod relief cutouts near the lower edge; volume_cm3=2632.01062; mass_kg=2.71097094
Volume GeoOpt_S1_PlasticFullWrap_SideShell_5mm
GeoOpt_S1_PlasticFullWrap_SideShell_5mm.Material PlasticScintillator
GeoOpt_S1_PlasticFullWrap_SideShell_5mm.Visibility 1
GeoOpt_S1_PlasticFullWrap_SideShell_5mm.Shape GeoOpt_S1_PlasticFullWrap_SideShell_5mm_ReliefStep02Shape
GeoOpt_S1_PlasticFullWrap_SideShell_5mm.Position 0 0 -7.95
GeoOpt_S1_PlasticFullWrap_SideShell_5mm.Mother InstrumentFrame
Shape PCON GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_FullDiskShape
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_FullDiskShape.Parameters 0 360 2 -0.25 0 27.9 0.25 0 27.9
Shape BRIK GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod03ReliefShape
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod03ReliefShape.Parameters 4 4 0.3
Orientation GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod03ReliefOrientation
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod03ReliefOrientation.Position -19.5 19.8 0
Shape BRIK GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod04ReliefShape
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod04ReliefShape.Parameters 4 4 0.3
Orientation GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod04ReliefOrientation
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod04ReliefOrientation.Position -19.5 -19.8 0
Shape Subtraction GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_ReliefStep01Shape
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_ReliefStep01Shape.Parameters GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_FullDiskShape GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod03ReliefShape GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod03ReliefOrientation
Shape Subtraction GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_ReliefStep02Shape
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_ReliefStep02Shape.Parameters GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_ReliefStep01Shape GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod04ReliefShape GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_NF2Rod04ReliefOrientation
// Volume GeoOpt_S1_PlasticFullWrap_BottomCap_5mm; role=Active plastic scintillator bottom skin closing the outer charged-particle veto envelope; includes two local NF2 outer-support rod relief cutouts; volume_cm3=1222.72357; mass_kg=1.25940528
Volume GeoOpt_S1_PlasticFullWrap_BottomCap_5mm
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm.Material PlasticScintillator
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm.Visibility 1
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm.Shape GeoOpt_S1_PlasticFullWrap_BottomCap_5mm_ReliefStep02Shape
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm.Position 0 0 -23.35
GeoOpt_S1_PlasticFullWrap_BottomCap_5mm.Mother InstrumentFrame
// Volume GeoOpt_S1_PlasticFullWrap_TopCap_5mm; role=Active plastic scintillator top annulus skin; preserves the existing central service/support opening; volume_cm3=536.584025; mass_kg=0.552681546
Volume GeoOpt_S1_PlasticFullWrap_TopCap_5mm
GeoOpt_S1_PlasticFullWrap_TopCap_5mm.Material PlasticScintillator
GeoOpt_S1_PlasticFullWrap_TopCap_5mm.Visibility 1
GeoOpt_S1_PlasticFullWrap_TopCap_5mm.Shape PCON 0 360 2 -0.25 20.9 27.9 0.25 20.9 27.9
GeoOpt_S1_PlasticFullWrap_TopCap_5mm.Position 0 0 7.45
GeoOpt_S1_PlasticFullWrap_TopCap_5mm.Mother InstrumentFrame
Shape PCON GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_FullShellShape
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_FullShellShape.Parameters 0 360 2 -14.15 26.4 27.4 14.15 26.4 27.4
Shape BRIK GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SignalWindowCutShape
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SignalWindowCutShape.Parameters 13.701 2.4 2.4
Orientation GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SignalWindowCutOrientation
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SignalWindowCutOrientation.Position -13.7 0 2.75
Shape Subtraction GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SubtractionShape
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SubtractionShape.Parameters GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_FullShellShape GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SignalWindowCutShape GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SignalWindowCutOrientation
// Volume GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm; role=1 cm borated polyethylene inner side shell with a rectangular negative-x signal-window cutout; kept inside the plastic scintillator skin so the BPE does not become the first passive charged-particle stop; volume_cm3=4783.20048; mass_kg=4.54404045
Volume GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm.Material BoratedPolyethylene5wtB
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm.Visibility 1
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm.Shape GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm_SubtractionShape
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm.Position 0 0 -7.95
GeoOpt_BPE5_FullWrap_SideShell_SignalWindowCut_10mm.Mother InstrumentFrame
// Volume GeoOpt_BPE5_FullWrap_BottomCap_10mm; role=1 cm borated polyethylene bottom cap inside the plastic skin and outside the W bottom baffle; volume_cm3=2358.5821; mass_kg=2.240653
Volume GeoOpt_BPE5_FullWrap_BottomCap_10mm
GeoOpt_BPE5_FullWrap_BottomCap_10mm.Material BoratedPolyethylene5wtB
GeoOpt_BPE5_FullWrap_BottomCap_10mm.Visibility 1
GeoOpt_BPE5_FullWrap_BottomCap_10mm.Shape PCON 0 360 2 -0.5 0 27.4 0.5 0 27.4
GeoOpt_BPE5_FullWrap_BottomCap_10mm.Position 0 0 -22.6
GeoOpt_BPE5_FullWrap_BottomCap_10mm.Mother InstrumentFrame
// Volume GeoOpt_BPE5_FullWrap_TopCap_10mm; role=1 cm borated polyethylene top annulus inside the plastic skin; preserves the existing central service/support opening; volume_cm3=986.303014; mass_kg=0.936987863
Volume GeoOpt_BPE5_FullWrap_TopCap_10mm
GeoOpt_BPE5_FullWrap_TopCap_10mm.Material BoratedPolyethylene5wtB
GeoOpt_BPE5_FullWrap_TopCap_10mm.Visibility 1
GeoOpt_BPE5_FullWrap_TopCap_10mm.Shape PCON 0 360 2 -0.5 20.9 27.4 0.5 20.9 27.4
GeoOpt_BPE5_FullWrap_TopCap_10mm.Position 0 0 6.7
GeoOpt_BPE5_FullWrap_TopCap_10mm.Mother InstrumentFrame
// Volume GeoOpt_W_BottomBaffle_5mm_R60; role=5 mm tungsten bottom baffle for lower-hemisphere atmospheric 511 keV photons; placed inward of the borated-polyethylene bottom layer and just outside the original Mass_model_511 bottom shell; volume_cm3=56.5486678; mass_kg=1.09138929
Volume GeoOpt_W_BottomBaffle_5mm_R60
GeoOpt_W_BottomBaffle_5mm_R60.Material W
GeoOpt_W_BottomBaffle_5mm_R60.Visibility 1
GeoOpt_W_BottomBaffle_5mm_R60.Shape PCON 0 360 2 -0.25 0 6 0.25 0 6
GeoOpt_W_BottomBaffle_5mm_R60.Position 0 0 -21.8
GeoOpt_W_BottomBaffle_5mm_R60.Mother InstrumentFrame
