#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List


ROOT = Path(__file__).resolve().parents[1]


DEFAULT_INPUTS = {
    "geant4_calibrated": "runs/channel/geant4_4ring_multibounce_calibrated/summary.json",
    "geant4_strict": "runs/channel/geant4_4ring_multibounce_paper_formula_strict/summary.json",
    "wallbywall": "runs/channel_wallbywall_rebuild/summary.json",
    "wallbywall_no_si": "runs/channel_wallbywall_rebuild_no_si_abs_smoke/summary.json",
    "wallbywall_contract": "runs/io_contract_validation_channel_wallbywall_rebuild/summary.json",
    "wallbywall_detector": "runs/geant4_detector_wallbywall_1k/summary.json",
    "wallbywall_detector_contract": "runs/io_contract_validation_channel_wallbywall_detector_1k/summary.json",
}


def read_json(path: str | Path) -> Dict[str, Any]:
    resolved = ROOT / path
    if not resolved.exists():
        raise FileNotFoundError(f"missing required input: {path}")
    return json.loads(resolved.read_text(encoding="utf-8"))


def metric_block(summary: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "system": summary.get("system"),
        "model": summary.get("model"),
        "n_primaries": summary.get("n_primaries"),
        "n_survived": summary.get("n_survived"),
        "transmissivity": summary.get("transmissivity"),
        "effective_area_cm2": summary.get("effective_area_cm2"),
        "spot_d90_cm": summary.get("spot_d90_cm"),
        "mean_bounces_per_survivor": summary.get("mean_bounces_per_survivor"),
        "mean_grazing_angle_rad": summary.get("mean_grazing_angle_rad"),
        "warning": summary.get("warning"),
    }


def detector_metric_block(summary: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "system": summary.get("system"),
        "model": summary.get("model"),
        "n_input_photons": summary.get("n_input_photons"),
        "n_simulated": summary.get("n_simulated"),
        "n_hits": summary.get("n_hits"),
        "n_tes_detected": summary.get("n_tes_detected"),
        "tes_detection_fraction": summary.get("tes_detection_fraction"),
        "n_bgo_veto": summary.get("n_bgo_veto"),
        "bgo_veto_fraction": summary.get("bgo_veto_fraction"),
        "warning": summary.get("warning"),
    }


def status_rows(inputs: Dict[str, Dict[str, Any]]) -> List[Dict[str, str]]:
    contract_ok = bool(inputs["wallbywall_contract"].get("ok"))
    detector_contract_ok = bool(inputs["wallbywall_detector_contract"].get("ok"))
    return [
        {
            "item": "A. Public-geometry wall-by-wall channel optics",
            "status": "DONE_CURRENT_STAGE" if contract_ok else "BLOCKED_CONTRACT",
            "evidence": (
                "Python wall-by-wall run writes phase_space/optics_history and passes optics-only IO contract"
                if contract_ok
                else "wall-by-wall contract did not pass"
            ),
            "claim_boundary": (
                "Natural bounce count and grazing angles are generated by 30/150 nm W/Si spacer geometry; "
                "not an exact original IDL reproduction because the original IDL/IMD artifacts are unavailable."
            ),
        },
        {
            "item": "B. Geant4 channel optics handoff",
            "status": "DONE_PARAMETERIZED",
            "evidence": "Geant4 4-ring multibounce run reproduces headline optics scale and writes contract outputs.",
            "claim_boundary": "This remains a parameterized table-driven path model, not full Geant4 wall-by-wall channel geometry.",
        },
        {
            "item": "C. Strict public-parameter pressure test",
            "status": "DONE_DIAGNOSTIC",
            "evidence": "Geant4 strict mode includes paper-bend, open-fraction, and Si path-absorption terms.",
            "claim_boundary": "Lower throughput is retained as a model-gap diagnostic, not tuned away.",
        },
        {
            "item": "D. IDL/IMD provenance recovery",
            "status": "OPEN_EXTERNAL_PROVENANCE",
            "evidence": "Local public-geometry reconstruction and dense Parratt table exist.",
            "claim_boundary": "Publication-grade closure still needs original IDL path accounting or independent IMD/DarpanX/CXRO export comparison.",
        },
        {
            "item": "E. Optics-to-detector handoff",
            "status": "DONE_END_TO_END_SMOKE" if detector_contract_ok else "READY_OPTICS_ONLY",
            "evidence": (
                "Wall-by-wall phase_space drives a 1k detector-only Geant4 smoke run and full contract passes."
                if detector_contract_ok
                else "Wall-by-wall phase_space.csv passes optics contract and can be used as detector input."
            ),
            "claim_boundary": "Detector result is still a minimal TES/BGO scaffold, not validated flight detector performance.",
        },
    ]


def build_summary(inputs: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    wall = inputs["wallbywall"]
    no_si = inputs["wallbywall_no_si"]
    g4 = inputs["geant4_calibrated"]
    strict = inputs["geant4_strict"]
    return {
        "status": "CHANNEL_PLAN_COMPLETE_CURRENT_STAGE",
        "completion_standard": (
            "Completed to the current evidence-backed stage: public-geometry wall-by-wall truth generator, "
            "parameterized Geant4 handoff, strict pressure test, and explicit open provenance gaps."
        ),
        "claim": {
            "high_confidence": [
                "Wall-by-wall Python reconstruction no longer forces n_bounce or grazing angle.",
                "Geant4 calibrated multibounce remains parameterized and should not be described as full wall-by-wall geometry.",
                "Wall-by-wall optics-only phase_space/optics_history contract passes.",
                "Wall-by-wall phase_space can drive the Geant4 detector-only scaffold and passes full source/detector contract in the 1k smoke run.",
            ],
            "medium_confidence": [
                "The public-geometry wall-by-wall result is a useful IDL/IMD-style truth-generator direction.",
                "The remaining 0.80-vs-public-geometry throughput gap is a model/provenance issue rather than simple plumbing.",
            ],
            "open": [
                "Original IDL source, IMD reflectivity export, and exact path/open-area/absorption accounting are not available locally.",
                "The detector-only run is a handoff smoke test, not a validated TES/BGO flight mass-model claim.",
            ],
        },
        "metrics": {
            "wallbywall_with_si_path_absorption": metric_block(wall),
            "wallbywall_without_si_path_absorption": metric_block(no_si),
            "geant4_calibrated_parameterized": metric_block(g4),
            "geant4_strict_public_parameter_pressure_test": metric_block(strict),
            "geant4_detector_wallbywall_1k": detector_metric_block(inputs["wallbywall_detector"]),
        },
        "comparisons": {
            "wallbywall_minus_geant4_calibrated_transmissivity": wall["transmissivity"] - g4["transmissivity"],
            "wallbywall_no_si_minus_geant4_calibrated_transmissivity": no_si["transmissivity"] - g4["transmissivity"],
            "strict_geant4_minus_wallbywall_transmissivity": strict["transmissivity"] - wall["transmissivity"],
            "wallbywall_survivor_mean_bounces": wall["mean_bounces_per_survivor"],
            "wallbywall_no_si_survivor_mean_bounces": no_si["mean_bounces_per_survivor"],
        },
        "plan_rows": status_rows(inputs),
        "contract": {
            "wallbywall_optics_only": inputs["wallbywall_contract"],
            "wallbywall_detector_1k": inputs["wallbywall_detector_contract"],
        },
        "next_checks": [
            "Add an independent IMD/DarpanX/CXRO-derived W/Si reflectivity table and compare against the current Parratt grid.",
            "If Geant4 full wall-by-wall remains required, port the Python wall-intersection kernel into a dedicated Geant4 geometry/process target rather than modeling nanolayers.",
            "Replace the detector-only scaffold with audited TES/BGO mass model and reconstruction before claiming detector performance.",
        ],
    }


def fmt(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def write_record(path: Path, summary: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    metrics = summary["metrics"]
    rows = summary["plan_rows"]
    lines = [
        "# Channel Optics Plan Completion",
        "",
        "## Completion Standard",
        "",
        summary["completion_standard"],
        "",
        "## Plan Status",
        "",
        "| item | status | evidence | claim boundary |",
        "| --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['item']} | {row['status']} | {row['evidence']} | {row['claim_boundary']} |"
        )
    lines.extend(
        [
            "",
            "## Key Metrics",
            "",
            "| run | n/input | survived/simulated | transmissivity/TES fraction | effective area cm2 | spot d90 cm | survivor mean bounces |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
    )
    for name, block in metrics.items():
        n_primary = block.get("n_primaries", block.get("n_input_photons"))
        n_survived = block.get("n_survived", block.get("n_simulated"))
        fraction = block.get("transmissivity", block.get("tes_detection_fraction"))
        lines.append(
            "| "
            + " | ".join(
                [
                    name,
                    fmt(n_primary),
                    fmt(n_survived),
                    fmt(fraction),
                    fmt(block.get("effective_area_cm2")),
                    fmt(block.get("spot_d90_cm")),
                    fmt(block.get("mean_bounces_per_survivor")),
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Confidence",
            "",
            "High confidence:",
        ]
    )
    lines.extend(f"- {item}" for item in summary["claim"]["high_confidence"])
    lines.append("")
    lines.append("Medium confidence:")
    lines.extend(f"- {item}" for item in summary["claim"]["medium_confidence"])
    lines.append("")
    lines.append("Open:")
    lines.extend(f"- {item}" for item in summary["claim"]["open"])
    lines.extend(
        [
            "",
            "## Next Checks",
            "",
        ]
    )
    lines.extend(f"- {item}" for item in summary["next_checks"])
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Complete and record the current channel optics plan status.")
    parser.add_argument("--out", default="runs/channel_optics_plan_completion/summary.json")
    parser.add_argument("--record", default="records/2026-05-21_channel_optics_plan_completion.md")
    for key, default in DEFAULT_INPUTS.items():
        parser.add_argument(f"--{key.replace('_', '-')}", default=default)
    args = parser.parse_args()

    inputs = {
        key: read_json(getattr(args, key))
        for key in DEFAULT_INPUTS
    }
    summary = build_summary(inputs)
    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_record(ROOT / args.record, summary)
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
