#!/usr/bin/env python3
"""Build a TES+CsI+external-support W-barrel hypothesis geometry.

The source geometry is read-only.  This builder keeps only the user-requested
active detector volumes and external supports, then adds a passive W barrel and
a thin Al side window.
"""

from __future__ import annotations

import json
import math
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle


ROOT = Path(__file__).resolve().parents[3]
WORK = Path(__file__).resolve().parent
GEOM_DIR = WORK / "geometry"
FIG_DIR = WORK / "figures"

SOURCE_GEOM_DIR = ROOT / "engineering/geometry_optimization_20260704/01_geo_opt_s1_bottomw_b4c/geometry"
SOURCE_GEO = SOURCE_GEOM_DIR / "DEMO2_DR_v3p5_minpatch_centerfinger_megalib_proxy.geo"
SOURCE_DET = SOURCE_GEOM_DIR / "DEMO2_DR_v3p5_minpatch_centerfinger_megalib_proxy.det"

LABEL = "Hyp_BarrelW_TES_CsI_ExternalSupport_20260707"
OUT_GEO = GEOM_DIR / f"{LABEL}.geo"
OUT_DET = GEOM_DIR / f"{LABEL}.det"
OUT_SETUP = GEOM_DIR / f"{LABEL}.geo.setup"
OUT_MATERIALS = GEOM_DIR / f"Materials_{LABEL}.geo"
OUT_MANIFEST = WORK / "barrel_hypothesis_geometry_manifest.json"
OUT_DETAIL_PNG = FIG_DIR / "hyp_barrel_w_tes_csi_2d_detail.png"
OUT_DETAIL_SVG = FIG_DIR / "hyp_barrel_w_tes_csi_2d_detail.svg"
OUT_WRL = FIG_DIR / "hyp_barrel_w_tes_csi.wrl"

BARREL = {
    "material": "W",
    "inner_radius_cm": 30.0,
    "outer_radius_cm": 33.0,
    "side_z_min_cm": -25.0,
    "side_z_max_cm": 10.0,
    "side_center_z_cm": -7.5,
    "side_half_height_cm": 17.5,
    "cap_thickness_cm": 3.0,
    "bottom_cap_center_z_cm": -26.5,
    "top_cap_center_z_cm": 11.5,
    "window_center_local_cm": [-30.0, 0.0, -5.2],
    "window_half_y_cm": 2.4,
    "window_half_z_cm": 2.4,
    "window_al_half_thickness_cm": 0.025,
}

ALLOWLIST_PREFIXES = (
    "TES_L",
    "TES_Pixel_L",
    "TP_L",
    "CsI_",
    "NF2_OuterSupport_",
)
ALLOWLIST_EXACT = {"WorldVolume", "InstrumentFrame"}
DENYLIST_PREFIXES = (
    "Vacuum_Jacket_",
    "Shield_60K_",
    "Shield_4K_",
    "Still_Shield_",
    "Plate_300K_",
    "Win_50mK_",
    "Win_Still_",
    "Win_4K_",
    "Win_60K_",
    "Win_Be_",
    "Win_Outer_",
    "DR_",
    "ColdPlate_",
    "Cu_ColdFinger_",
    "Cu_MXC_",
    "Cu_SubstrateSupport_",
    "Si_Substrate_",
    "GeoOpt_S1_PlasticFullWrap_",
    "GeoOpt_BPE5_",
    "GeoOpt_W_BottomBaffle_",
)


def now_utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return p.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def allowed_name(name: str) -> bool:
    return name in ALLOWLIST_EXACT or any(name.startswith(prefix) for prefix in ALLOWLIST_PREFIXES)


def denied_name(name: str) -> bool:
    return any(name.startswith(prefix) for prefix in DENYLIST_PREFIXES)


def volume_name_from_line(line: str) -> str | None:
    if line.startswith("Volume "):
        return line.split(None, 1)[1].strip()
    return None


def copy_name_from_line(line: str) -> tuple[str, str] | None:
    match = re.match(r"^([A-Za-z0-9_]+)\.Copy\s+([A-Za-z0-9_]+)\s*$", line.strip())
    if not match:
        return None
    return match.group(1), match.group(2)


def collect_block(lines: list[str], start: int) -> tuple[list[str], int]:
    block = [lines[start]]
    i = start + 1
    while i < len(lines):
        block.append(lines[i])
        if lines[i].strip() == "":
            i += 1
            break
        i += 1
    return block, i


def shape_allowed(name: str) -> bool:
    return name.startswith(("CsI_", "TES_", "TP_", "NF2_OuterSupport_", "Hyp_"))


def line_has_deny_token(line: str) -> bool:
    return any(token in line for token in DENYLIST_PREFIXES)


def property_prefix(line: str) -> str | None:
    match = re.match(r"^([A-Za-z0-9_]+)\.", line.strip())
    return match.group(1) if match else None


def filter_geo() -> dict[str, Any]:
    lines = SOURCE_GEO.read_text(encoding="utf-8", errors="ignore").splitlines()
    out: list[str] = [
        f"// {LABEL}",
        "// Generated by build_barrel_hypothesis_geometry.py",
        f"Include {OUT_MATERIALS.name}",
        "",
        "Name HypBarrelW_TES_CsI_ExternalSupport",
        "Version 1",
        "",
        "Volume WorldVolume",
        "WorldVolume.Visibility 0",
        "WorldVolume.Material Vacuum",
        "WorldVolume.Shape BRIK 1000 1000 1000",
        "WorldVolume.Mother 0",
        "",
        "Volume InstrumentFrame",
        "InstrumentFrame.Visibility 0",
        "InstrumentFrame.Material Vacuum",
        "InstrumentFrame.Shape BRIK 80 80 80",
        "InstrumentFrame.Position 0 0 0",
        "InstrumentFrame.Rotation 0 45 0",
        "InstrumentFrame.Mother WorldVolume",
        "",
    ]
    kept: list[str] = ["WorldVolume", "InstrumentFrame"]
    removed: list[str] = []
    denied_removed: list[str] = []
    for line in lines:
        if line.startswith("Include Intro_"):
            continue
        vol = volume_name_from_line(line)
        copy = copy_name_from_line(line)
        if vol is not None:
            if vol in ALLOWLIST_EXACT:
                # The generated intro above defines these containers.
                kept.append(vol)
            elif allowed_name(vol):
                out.append(line)
                kept.append(vol)
            else:
                removed.append(vol)
                if denied_name(vol):
                    denied_removed.append(vol)
            continue
        if copy is not None:
            base, inst = copy
            if allowed_name(base) or allowed_name(inst):
                out.append(line)
                kept.append(inst)
            else:
                removed.append(inst)
                if denied_name(inst) or denied_name(base):
                    denied_removed.append(inst)
            continue
        if not line.strip():
            out.append(line)
            continue
        if line_has_deny_token(line):
            continue
        if line.startswith("// Volume "):
            name = line.split("Volume ", 1)[1].split(";", 1)[0].strip()
            if allowed_name(name):
                out.append(line)
            continue
        if line.startswith("//"):
            # Drop old construction comments that are unrelated to retained
            # volumes; they otherwise obscure the allowlist audit.
            if any(prefix in line for prefix in ("TES_", "TP_", "CsI_", "NF2_OuterSupport_")):
                out.append(line)
            continue
        if line.startswith("Shape "):
            parts = line.split()
            shape_name = parts[2] if len(parts) >= 3 and parts[1] != "Subtraction" else (parts[2] if len(parts) >= 3 else "")
            if shape_allowed(shape_name):
                out.append(line)
            continue
        if line.startswith("Orientation "):
            parts = line.split()
            if len(parts) >= 2 and shape_allowed(parts[1]):
                out.append(line)
            continue
        prefix = property_prefix(line)
        if prefix is not None:
            if allowed_name(prefix) or shape_allowed(prefix):
                out.append(line)
            continue
        # Keep other neutral MEGAlib syntax only when it is not tied to a
        # removed structure.
        out.append(line)

    out.extend(barrel_geo_lines())
    OUT_GEO.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    return {
        "kept_names": sorted(set(kept)),
        "removed_names": sorted(set(removed)),
        "denylist_removed": sorted(set(denied_removed)),
        "kept_counts_by_prefix": count_by_prefix(kept),
        "removed_counts_by_prefix": count_by_prefix(removed),
    }


def count_by_prefix(names: list[str]) -> dict[str, int]:
    prefixes = {
        "TES": "TES_",
        "TP": "TP_",
        "CsI": "CsI_",
        "NF2_OuterSupport": "NF2_OuterSupport_",
        "GeoOpt": "GeoOpt_",
        "CryostatWindowShell": "Vacuum_Jacket_|Shield_|Still_Shield_|Plate_|Win_",
        "DRCold": "DR_|ColdPlate_|Cu_ColdFinger_|Cu_MXC_|Cu_SubstrateSupport_|Si_Substrate_",
    }
    out: dict[str, int] = {}
    for label, prefix_expr in prefixes.items():
        parts = prefix_expr.split("|")
        out[label] = sum(1 for name in names if any(name.startswith(part) for part in parts))
    out["total"] = len(set(names))
    return out


def barrel_geo_lines() -> list[str]:
    b = BARREL
    x_cut = b["outer_radius_cm"] + 1.0
    win_x = -b["outer_radius_cm"]
    win_z_shape = b["window_center_local_cm"][2] - b["side_center_z_cm"]
    side_volume_cm3 = math.pi * (b["outer_radius_cm"] ** 2 - b["inner_radius_cm"] ** 2) * (b["side_z_max_cm"] - b["side_z_min_cm"])
    cap_volume_cm3 = math.pi * b["outer_radius_cm"] ** 2 * b["cap_thickness_cm"]
    al_volume_cm3 = (2 * b["window_al_half_thickness_cm"]) * (2 * b["window_half_y_cm"]) * (2 * b["window_half_z_cm"])
    return [
        "",
        "// BEGIN HYPOTHESIS_PASSIVE_BARREL_W",
        "Shape PCON Hyp_W_Barrel_SideShell_WindowCut_FullShape",
        (
            "Hyp_W_Barrel_SideShell_WindowCut_FullShape.Parameters "
            f"0 360 2 {-b['side_half_height_cm']} {b['inner_radius_cm']} {b['outer_radius_cm']} "
            f"{b['side_half_height_cm']} {b['inner_radius_cm']} {b['outer_radius_cm']}"
        ),
        "Shape BRIK Hyp_W_Barrel_SideShell_WindowCut_CutShape",
        (
            "Hyp_W_Barrel_SideShell_WindowCut_CutShape.Parameters "
            f"{x_cut:.6g} {b['window_half_y_cm']:.6g} {b['window_half_z_cm']:.6g}"
        ),
        "Orientation Hyp_W_Barrel_SideShell_WindowCut_CutOrientation",
        f"Hyp_W_Barrel_SideShell_WindowCut_CutOrientation.Position {win_x:.6g} 0 {win_z_shape:.6g}",
        "Shape Subtraction Hyp_W_Barrel_SideShell_WindowCut_Shape",
        "Hyp_W_Barrel_SideShell_WindowCut_Shape.Parameters Hyp_W_Barrel_SideShell_WindowCut_FullShape Hyp_W_Barrel_SideShell_WindowCut_CutShape Hyp_W_Barrel_SideShell_WindowCut_CutOrientation",
        f"// Volume Hyp_W_Barrel_SideShell_WindowCut; role=passive W barrel side wall with negative-x side-window cut; approx_volume_cm3={side_volume_cm3:.6g}; approx_mass_kg={side_volume_cm3 * 19.3 / 1000:.6g}",
        "Volume Hyp_W_Barrel_SideShell_WindowCut",
        "Hyp_W_Barrel_SideShell_WindowCut.Material W",
        "Hyp_W_Barrel_SideShell_WindowCut.Visibility 1",
        "Hyp_W_Barrel_SideShell_WindowCut.Shape Hyp_W_Barrel_SideShell_WindowCut_Shape",
        f"Hyp_W_Barrel_SideShell_WindowCut.Position 0 0 {b['side_center_z_cm']:.6g}",
        "Hyp_W_Barrel_SideShell_WindowCut.Mother InstrumentFrame",
        "",
        f"// Volume Hyp_W_Barrel_BottomCap; role=passive W bottom cap; approx_volume_cm3={cap_volume_cm3:.6g}; approx_mass_kg={cap_volume_cm3 * 19.3 / 1000:.6g}",
        "Volume Hyp_W_Barrel_BottomCap",
        "Hyp_W_Barrel_BottomCap.Material W",
        "Hyp_W_Barrel_BottomCap.Visibility 1",
        f"Hyp_W_Barrel_BottomCap.Shape PCON 0 360 2 {-b['cap_thickness_cm']/2:.6g} 0 {b['outer_radius_cm']} {b['cap_thickness_cm']/2:.6g} 0 {b['outer_radius_cm']}",
        f"Hyp_W_Barrel_BottomCap.Position 0 0 {b['bottom_cap_center_z_cm']:.6g}",
        "Hyp_W_Barrel_BottomCap.Mother InstrumentFrame",
        "",
        f"// Volume Hyp_W_Barrel_TopCap; role=passive W top cap; approx_volume_cm3={cap_volume_cm3:.6g}; approx_mass_kg={cap_volume_cm3 * 19.3 / 1000:.6g}",
        "Volume Hyp_W_Barrel_TopCap",
        "Hyp_W_Barrel_TopCap.Material W",
        "Hyp_W_Barrel_TopCap.Visibility 1",
        f"Hyp_W_Barrel_TopCap.Shape PCON 0 360 2 {-b['cap_thickness_cm']/2:.6g} 0 {b['outer_radius_cm']} {b['cap_thickness_cm']/2:.6g} 0 {b['outer_radius_cm']}",
        f"Hyp_W_Barrel_TopCap.Position 0 0 {b['top_cap_center_z_cm']:.6g}",
        "Hyp_W_Barrel_TopCap.Mother InstrumentFrame",
        "",
        f"// Volume Hyp_Al_SideWindow_Thin; role=thin passive Al side window in barrel cutout; approx_volume_cm3={al_volume_cm3:.6g}; approx_mass_g={al_volume_cm3 * 2.7:.6g}",
        "Volume Hyp_Al_SideWindow_Thin",
        "Hyp_Al_SideWindow_Thin.Material Aluminium",
        "Hyp_Al_SideWindow_Thin.Visibility 1",
        (
            "Hyp_Al_SideWindow_Thin.Shape BRIK "
            f"{b['window_al_half_thickness_cm']:.6g} {b['window_half_y_cm']:.6g} {b['window_half_z_cm']:.6g}"
        ),
        (
            "Hyp_Al_SideWindow_Thin.Position "
            f"{b['window_center_local_cm'][0]:.6g} {b['window_center_local_cm'][1]:.6g} {b['window_center_local_cm'][2]:.6g}"
        ),
        "Hyp_Al_SideWindow_Thin.Mother InstrumentFrame",
        "// END HYPOTHESIS_PASSIVE_BARREL_W",
        "",
    ]


def filter_det() -> dict[str, Any]:
    lines = SOURCE_DET.read_text(encoding="utf-8", errors="ignore").splitlines()
    out = [f"// {LABEL} detector map", "// Retains TES MDCalorimeters and CsI scintillator active veto only.", ""]
    kept: list[str] = []
    removed: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if not (line.startswith("MDCalorimeter ") or line.startswith("Scintillator ")):
            i += 1
            continue
        block, j = collect_block(lines, i)
        name = line.split(None, 1)[1].strip()
        text = "\n".join(block)
        if line.startswith("MDCalorimeter ") and name in {"D1", "D2", "D3", "D4", "D5", "D6"}:
            out.extend(block)
            kept.append(name)
        elif line.startswith("Scintillator ") and ".SensitiveVolume CsI_" in text:
            out.extend(block)
            kept.append(name)
        else:
            removed.append(name)
        i = j
    OUT_DET.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    return {"kept_detector_entries": kept, "removed_detector_entries": removed}


def write_materials() -> None:
    OUT_MATERIALS.write_text(
        """# Minimal materials for TES+CsI+external-support W-barrel hypothesis.
Include $(MEGALIB)/resource/examples/geomega/materials/Materials.geo

Material Nb
Nb.Density 8.57
Nb.Component Nb 1

Material W
W.Density 19.3
W.Component W 1

Material Ta
Ta.Density 16.69
Ta.Component Ta 1

Material Be
Be.Density 1.85
Be.Component Be 1

Material StainlessSteel
StainlessSteel.Density 8
StainlessSteel.Component Fe 70
StainlessSteel.Component Cr 18
StainlessSteel.Component Ni 10
StainlessSteel.Component Mn 2

Material G10
G10.Density 1.85
G10.Component Si 1
G10.Component O 2
G10.Component C 3
G10.Component H 3
""",
        encoding="utf-8",
    )


def write_setup() -> None:
    OUT_SETUP.write_text(
        f"""Name {LABEL}
Version 1
Include {OUT_GEO.name}
Include {OUT_DET.name}
SurroundingSphere 80 0 0 0 80
""",
        encoding="utf-8",
    )


def write_figures() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    b = BARREL
    fig, ax = plt.subplots(figsize=(8, 5.5))
    ax.add_patch(
        Rectangle(
            (-b["outer_radius_cm"], b["side_z_min_cm"]),
            2 * b["outer_radius_cm"],
            b["side_z_max_cm"] - b["side_z_min_cm"],
            facecolor="#d8d8d8",
            edgecolor="#555555",
            alpha=0.35,
            label="W barrel outer envelope",
        )
    )
    ax.add_patch(
        Rectangle(
            (-b["inner_radius_cm"], b["side_z_min_cm"]),
            2 * b["inner_radius_cm"],
            b["side_z_max_cm"] - b["side_z_min_cm"],
            facecolor="white",
            edgecolor="#888888",
            alpha=1.0,
            label="barrel cavity",
        )
    )
    ax.add_patch(Rectangle((-33, -28), 66, 3, facecolor="#b0b0b0", edgecolor="#555555", alpha=0.55))
    ax.add_patch(Rectangle((-33, 10), 66, 3, facecolor="#b0b0b0", edgecolor="#555555", alpha=0.55))
    ax.add_patch(
        Rectangle(
            (-33, -7.6),
            3.2,
            4.8,
            facecolor="#f3c64e",
            edgecolor="#8a6b00",
            label="thin Al side window",
        )
    )
    ax.add_patch(Rectangle((-3.2, -7.0), 7.0, 3.6, facecolor="#d64b4b", edgecolor="#7a1717", label="TES stack proxy"))
    ax.add_patch(Rectangle((-25.2, -14.4), 4.0, 16.4, facecolor="#5aa1d6", edgecolor="#174b7a", alpha=0.45, label="CsI side shell proxy"))
    ax.add_patch(Rectangle((21.2, -14.4), 4.0, 16.4, facecolor="#5aa1d6", edgecolor="#174b7a", alpha=0.45))
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("instrument local x (cm)")
    ax.set_ylabel("instrument local z (cm)")
    ax.set_xlim(-40, 40)
    ax.set_ylim(-32, 16)
    ax.legend(loc="upper right", fontsize=8)
    ax.grid(True, color="#dddddd", linewidth=0.5)
    fig.tight_layout()
    fig.savefig(OUT_DETAIL_PNG, dpi=180)
    fig.savefig(OUT_DETAIL_SVG)
    plt.close(fig)

    OUT_WRL.write_text(
        """#VRML V2.0 utf8
WorldInfo { title "Hyp barrel W TES CsI external support preview" }
NavigationInfo { type ["EXAMINE", "ANY"] }
Viewpoint { position 0 -100 20 orientation 1 0 0 1.35 description "barrel overview" }
Transform {
  translation 0 0 -7.5
  children [
    Shape {
      appearance Appearance { material Material { diffuseColor 0.65 0.65 0.65 transparency 0.55 } }
      geometry Cylinder { radius 33 height 35 }
    }
  ]
}
Transform {
  translation -30 0 -5.2
  children [
    Shape {
      appearance Appearance { material Material { diffuseColor 1.0 0.75 0.1 transparency 0.05 } }
      geometry Box { size 0.05 4.8 4.8 }
    }
  ]
}
Transform {
  translation 0 0 -5.2
  children [
    Shape {
      appearance Appearance { material Material { diffuseColor 0.85 0.10 0.10 transparency 0.0 } }
      geometry Box { size 6.6 3.6 3.6 }
    }
  ]
}
""",
        encoding="utf-8",
    )


def main() -> int:
    GEOM_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    write_materials()
    geo_report = filter_geo()
    det_report = filter_det()
    write_setup()
    write_figures()

    side_volume_cm3 = math.pi * (BARREL["outer_radius_cm"] ** 2 - BARREL["inner_radius_cm"] ** 2) * (
        BARREL["side_z_max_cm"] - BARREL["side_z_min_cm"]
    )
    cap_volume_cm3 = math.pi * BARREL["outer_radius_cm"] ** 2 * BARREL["cap_thickness_cm"]
    al_volume_cm3 = (
        2
        * BARREL["window_al_half_thickness_cm"]
        * 2
        * BARREL["window_half_y_cm"]
        * 2
        * BARREL["window_half_z_cm"]
    )
    manifest = {
        "status": "PASS_BUILD_HYPOTHESIS_GEOMETRY_NOT_TRANSPORT_VALIDATED",
        "generated_at_utc": now_utc(),
        "source_geometry": rel(SOURCE_GEO),
        "source_detector": rel(SOURCE_DET),
        "generated_geometry_setup": rel(OUT_SETUP),
        "generated_geometry": rel(OUT_GEO),
        "generated_detector": rel(OUT_DET),
        "generated_materials": rel(OUT_MATERIALS),
        "figures": {"detail_png": rel(OUT_DETAIL_PNG), "detail_svg": rel(OUT_DETAIL_SVG), "wrl": rel(OUT_WRL)},
        "barrel": {
            **BARREL,
            "side_wall_volume_cm3": side_volume_cm3,
            "one_cap_volume_cm3": cap_volume_cm3,
            "total_w_volume_cm3": side_volume_cm3 + 2 * cap_volume_cm3,
            "total_w_mass_kg": (side_volume_cm3 + 2 * cap_volume_cm3) * 19.3 / 1000.0,
            "thin_al_window_volume_cm3": al_volume_cm3,
            "thin_al_window_mass_g": al_volume_cm3 * 2.7,
            "active_veto_status": "passive only; not counted as active veto energy",
        },
        "allowlist_prefixes": list(ALLOWLIST_PREFIXES),
        "allowlist_exact": sorted(ALLOWLIST_EXACT),
        "denylist_prefixes": list(DENYLIST_PREFIXES),
        "geometry_filter_report": geo_report,
        "detector_filter_report": det_report,
        "review_notes": [
            "Retains TES and CsI position/shape definitions by copying their current geometry blocks.",
            "Retains NF2_OuterSupport_* as explicit external support volumes.",
            "Removes current GeoOpt plastic/BPE/W add-ons to isolate passive barrel hypothesis.",
            "Does not retain internal cryostat/passive shell/window/DR/coldplate stacks.",
            "Passive W/Al barrel deposits must not be included in active anticoincidence; CsI is the retained active veto.",
        ],
    }
    OUT_MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"status": manifest["status"], "setup": rel(OUT_SETUP), "manifest": rel(OUT_MANIFEST)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
