#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build mono and Doppler-broadened 511 keV science source files."""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from pathlib import Path
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = ROOT / "configs" / "nextphase" / "science_511_line_models.yaml"
DEFAULT_TEMPLATE = ROOT / "run_configs" / "Science_511_onaxis_focalbeam_local.source"
DEFAULT_OUT = ROOT / "run_configs" / "nextphase_science_sources"
DEFAULT_REPORT = ROOT / "reports" / "nextphase_511" / "science_line_models"
C_KM_S = 299792.458


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def gaussian_pdf(e: np.ndarray, mu: float, sigma: float) -> np.ndarray:
    y = np.exp(-0.5 * ((e - mu) / sigma) ** 2)
    area = np.trapezoid(y, e)
    return y / area if area > 0 else y


def sigma_for_model(model: dict[str, Any], e0: float) -> float:
    typ = model["type"]
    if typ == "mono":
        return 0.0
    if typ == "gaussian":
        return float(model["fwhm_keV"]) / 2.3548200450309493
    if typ == "velocity_gaussian":
        return e0 * float(model["sigma_v_km_s"]) / C_KM_S
    raise ValueError(f"Unsupported model type: {typ}")


def fraction_in_window(e: np.ndarray, pdf: np.ndarray, lo: float, hi: float) -> float:
    mask = (e >= lo) & (e <= hi)
    if not np.any(mask):
        return 0.0
    total = np.trapezoid(pdf, e)
    part = np.trapezoid(pdf[mask], e[mask])
    return float(part / total) if total > 0 else 0.0


def replace_source_lines(template: str, model_id: str, spectrum_line: str, output_prefix: str) -> str:
    text = template
    text = re.sub(r"Science511\.FileName\s+\S+", f"Science511.FileName {output_prefix}", text)
    text = re.sub(r"Science511_OnAxis\.Spectrum\s+.*", spectrum_line, text)
    text = re.sub(r"Seed\s+\d+", f"Seed {5112026 + abs(hash(model_id)) % 100000}", text)
    header = (
        "# Generated by tools/build_science_511_line_sources.py.\n"
        f"# line_model_id={model_id}\n"
    )
    return header + text


def write_spectrum(path: Path, e: np.ndarray, pdf: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        fh.write("IP LIN\n")
        for x, y in zip(e, pdf):
            fh.write(f"DP {x:.8e} {y:.12e}\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    ap.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--report-out", type=Path, default=DEFAULT_REPORT)
    args = ap.parse_args()

    cfg = load_json(args.config)
    template = args.template.read_text(encoding="utf-8", errors="ignore")
    args.out.mkdir(parents=True, exist_ok=True)
    spectra_dir = args.out / "spectra"
    sim_dir = ROOT / "science_511_onaxis_source" / "nextphase_line_models"
    sim_dir.mkdir(parents=True, exist_ok=True)
    args.report_out.mkdir(parents=True, exist_ok=True)

    e0 = float(cfg["E0_keV"])
    binw = float(cfg["bin_width_keV"])
    e = np.arange(float(cfg["energy_min_keV"]), float(cfg["energy_max_keV"]) + 0.5 * binw, binw)
    rows = []
    manifest = []
    for model in cfg["models"]:
        model_id = str(model["id"])
        sigma = sigma_for_model(model, e0)
        source_path = args.out / f"Science511_{model_id}.source"
        if sigma == 0.0:
            spectrum_line = f"Science511_OnAxis.Spectrum Mono {e0:.6f}"
            spectrum_path = ""
            pdf = np.zeros_like(e)
            pdf[np.argmin(np.abs(e - e0))] = 1.0 / binw
            frac_480_550 = 1.0 if 480.0 <= e0 <= 550.0 else 0.0
            frac_line = 1.0 if 510.3 <= e0 <= 511.8 else 0.0
        else:
            pdf = gaussian_pdf(e, e0, sigma)
            spectrum_path_obj = spectra_dir / f"science_511_{model_id}.dat"
            write_spectrum(spectrum_path_obj, e, pdf)
            spectrum_path = rel(spectrum_path_obj)
            spectrum_line = f"Science511_OnAxis.Spectrum File {spectrum_path}"
            frac_480_550 = fraction_in_window(e, pdf, 480.0, 550.0)
            frac_line = fraction_in_window(e, pdf, 510.3, 511.8)

        output_prefix = rel(sim_dir / f"Science511_{model_id}")
        source_text = replace_source_lines(template, model_id, spectrum_line, output_prefix)
        source_path.write_text(source_text, encoding="utf-8")
        fwhm = 2.3548200450309493 * sigma
        rows.append({
            "model_id": model_id,
            "type": model["type"],
            "sigma_src_keV": f"{sigma:.12g}",
            "fwhm_src_keV": f"{fwhm:.12g}",
            "fraction_480_550": f"{frac_480_550:.12g}",
            "fraction_510p3_511p8": f"{frac_line:.12g}",
            "source_file": rel(source_path),
            "spectrum_file": spectrum_path,
            "output_prefix": output_prefix,
        })
        manifest.append(rel(source_path))

    csv_path = args.report_out / "source_fraction_in_windows.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as fh:
        fields = list(rows[0].keys())
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)

    (args.report_out / "science_line_source_manifest.json").write_text(
        json.dumps({"sources": manifest, "config": rel(args.config), "template": rel(args.template)}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    md = "# Science 511 line-model sources\n\n"
    md += "Generated source files keep the same beam geometry as the template and change only the line spectrum/output prefix.\n\n"
    md += "| model | FWHM keV | fraction 480-550 | fraction 510.3-511.8 | source |\n"
    md += "|---|---:|---:|---:|---|\n"
    for r in rows:
        md += f"| {r['model_id']} | {r['fwhm_src_keV']} | {r['fraction_480_550']} | {r['fraction_510p3_511p8']} | `{r['source_file']}` |\n"
    (args.report_out / "science_line_model_summary.md").write_text(md, encoding="utf-8")

    print(json.dumps({"sources_written": len(rows), "out": rel(args.out), "report_out": rel(args.report_out)}, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
